Crash:
rustc 1.24.0-nightly (0077d128d 2017-12-14)
cargo 0.25.0-nightly (930f9d949 2017-12-05)

cargo build --release

````
   Compiling rustc_crashtest_lto v0.1.0 (file:///tmp/rustc_crashtest_lto)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (0077d128d 2017-12-14) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'assertion failed: !sess.lto()', /checkout/src/librustc_trans/back/link.rs:1292:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `rustc_crashtest_lto`.

To learn more, run the command again with --verbose.
````

````
   Compiling rustc_crashtest_lto v0.1.0 (file:///tmp/rustc_crashtest_lto)
     Running `rustc --crate-name rustc_crashtest_lto src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=5f11b32eba9bdd4b -C extra-filename=-5f11b32eba9bdd4b --out-dir /tmp/rustc_crashtest_lto/target/release/deps -L dependency=/tmp/rustc_crashtest_lto/target/release/deps -C target-cpu=native`
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (0077d128d 2017-12-14) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: !sess.lto()', /checkout/src/librustc_trans/back/link.rs:1292:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_trans::back::link::link_natively
   7: rustc_trans::back::link::link_binary
   8: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::link_binary
   9: rustc_driver::driver::compile_input
  10: rustc_driver::run_compiler

error: Could not compile `rustc_crashtest_lto`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_crashtest_lto src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=5f11b32eba9bdd4b -C extra-filename=-5f11b32eba9bdd4b --out-dir /tmp/rustc_crashtest_lto/target/release/deps -L dependency=/tmp/rustc_crashtest_lto/target/release/deps -C target-cpu=native` (exit code: 101)

````